[project]
name = "frontend"
version = "1.0.0"
description = "Jac client application: frontend"
entry-point = "main.jac"

[dependencies]
paramiko = ">=0.0.0"

[dependencies.npm]
jac-client-node = "1.0.4"
recharts = "latest"
sonner = "latest"
react-router-dom = "latest"
tailwindcss = "latest"
"@tailwindcss/vite" = "latest"
tailwind-merge = "latest"
clsx = "latest"
watchdog = "latest"
"@vitejs/plugin-react" = "latest"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client.vite]
plugins = ["jacExtensionFix()", "tailwindcss()"]
lib_imports = [
    "import tailwindcss from '@tailwindcss/vite'",
    '''
function jacExtensionFix() {
  return {
    name: "jac-extension-fix",
    enforce: "pre",
    async resolveId(source, importer) {
      if (source.endsWith(".cl.jac")) {
        const newSource = source.replace(/\.cl\.jac$/, ".js");
        const resolution = await this.resolve(newSource, importer, { skipSelf: true });
        if (resolution) return resolution;
      }
      return null;
    }
  };
}
'''
]
